
// note
// creating this file for dummy data
// products list ke under product hai wo hai product model jo banya hai

import 'package:mahalaxmi_shop/models/product.dart';

var products = [
  Product(
    id: "1",
    name: "Mobile",
    category: "Electronic",
    averageRating: 0,
    createAt: "",
    description: "This is Mobile",
    discount: 0.0,
    discountEndData: "",
    discountStartDate: "",
    images: [],
    isActive: true,
    purchasePrice: 12000,
    sellPrice: 15000,
    unit: "Pic",
    reviews: [],
    stock: 12,
    supplier: "Ni30 Roy",
    tags: ["Mobile", "Electronic"],
    unitPrice: 15000,
    updatedAt: "",
  ),
  Product(
    id: "2",
    name: "Laptop",
    category: "Electronic",
    averageRating: 0,
    createAt: "",
    description: "This is Laptop",
    discount: 0.1,
    discountEndData: "",
    discountStartDate: "",
    images: [],
    isActive: true,
    purchasePrice: 50000,
    sellPrice: 55000,
    unit: "Piece",
    reviews: [],
    stock: 5,
    supplier: "Tech World",
    tags: ["Laptop", "Electronic"],
    unitPrice: 55000,
    updatedAt: "",
  ),
  Product(
    id: "3",
    name: "Headphone",
    category: "Electronic",
    averageRating: 0,
    createAt: "",
    description: "This is Headphone",
    discount: 0.05,
    discountEndData: "",
    discountStartDate: "",
    images: [],
    isActive: true,
    purchasePrice: 2000,
    sellPrice: 2500,
    unit: "Piece",
    reviews: [],
    stock: 20,
    supplier: "Sound Blast",
    tags: ["Headphone", "Electronic"],
    unitPrice: 2500,
    updatedAt: "",
  ),
  Product(
    id: "4",
    name: "Tablet",
    category: "Electronic",
    averageRating: 0,
    createAt: "",
    description: "This is Tablet",
    discount: 0.0,
    discountEndData: "",
    discountStartDate: "",
    images: [],
    isActive: true,
    purchasePrice: 15000,
    sellPrice: 18000,
    unit: "Piece",
    reviews: [],
    stock: 10,
    supplier: "Gadget Hub",
    tags: ["Tablet", "Electronic"],
    unitPrice: 18000,
    updatedAt: "",
  ),
  Product(
    id: "5",
    name: "Smartwatch",
    category: "Electronic",
    averageRating: 0,
    createAt: "",
    description: "This is Smartwatch",
    discount: 0.02,
    discountEndData: "",
    discountStartDate: "",
    images: [],
    isActive: true,
    purchasePrice: 8000,
    sellPrice: 10000,
    unit: "Piece",
    reviews: [],
    stock: 15,
    supplier: "Wrist Tech",
    tags: ["Smartwatch", "Electronic"],
    unitPrice: 10000,
    updatedAt: "",
  ),
  Product(
    id: "6",
    name: "Camera",
    category: "Electronic",
    averageRating: 0,
    createAt: "",
    description: "This is Camera",
    discount: 0.1,
    discountEndData: "",
    discountStartDate: "",
    images: [],
    isActive: true,
    purchasePrice: 30000,
    sellPrice: 35000,
    unit: "Piece",
    reviews: [],
    stock: 8,
    supplier: "Photo Gear",
    tags: ["Camera", "Electronic"],
    unitPrice: 35000,
    updatedAt: "",
  ),
  Product(
    id: "7",
    name: "Speaker",
    category: "Electronic",
    averageRating: 0,
    createAt: "",
    description: "This is Speaker",
    discount: 0.05,
    discountEndData: "",
    discountStartDate: "",
    images: [],
    isActive: true,
    purchasePrice: 4000,
    sellPrice: 5000,
    unit: "Piece",
    reviews: [],
    stock: 25,
    supplier: "Sound Blast",
    tags: ["Speaker", "Electronic"],
    unitPrice: 5000,
    updatedAt: "",
  ),
  Product(
    id: "8",
    name: "Monitor",
    category: "Electronic",
    averageRating: 0,
    createAt: "",
    description: "This is Monitor",
    discount: 0.15,
    discountEndData: "",
    discountStartDate: "",
    images: [],
    isActive: true,
    purchasePrice: 10000,
    sellPrice: 12000,
    unit: "Piece",
    reviews: [],
    stock: 7,
    supplier: "Display World",
    tags: ["Monitor", "Electronic"],
    unitPrice: 12000,
    updatedAt: "",
  ),
  Product(
    id: "9",
    name: "Keyboard",
    category: "Electronic",
    averageRating: 0,
    createAt: "",
    description: "This is Keyboard",
    discount: 0.05,
    discountEndData: "",
    discountStartDate: "",
    images: [],
    isActive: true,
    purchasePrice: 1500,
    sellPrice: 2000,
    unit: "Piece",
    reviews: [],
    stock: 30,
    supplier: "Tech World",
    tags: ["Keyboard", "Electronic"],
    unitPrice: 2000,
    updatedAt: "",
  ),
  Product(
    id: "10",
    name: "Mouse",
    category: "Electronic",
    averageRating: 0,
    createAt: "",
    description: "This is Mouse",
    discount: 0.1,
    discountEndData: "",
    discountStartDate: "",
    images: [],
    isActive: true,
    purchasePrice: 800,
    sellPrice: 1000,
    unit: "Piece",
    reviews: [],
    stock: 40,
    supplier: "Gadget Hub",
    tags: ["Mouse", "Electronic"],
    unitPrice: 1000,
    updatedAt: "",
  ),
  Product(
    id: "11",
    name: "Printer",
    category: "Electronic",
    averageRating: 0,
    createAt: "",
    description: "This is Printer",
    discount: 0.2,
    discountEndData: "",
    discountStartDate: "",
    images: [],
    isActive: true,
    purchasePrice: 15000,
    sellPrice: 18000,
    unit: "Piece",
    reviews: [],
    stock: 6,
    supplier: "Print Solutions",
    tags: ["Printer", "Electronic"],
    unitPrice: 18000,
    updatedAt: "",
  ),
];